wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1650952921
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      4: 3.7.13
      5: 0.12.15
      8:
      - 1
      - 5
channel_combos:
  desc: null
  value:
  - 64
  - 128
  - 192
  - 256
  - 512
dropout:
  desc: null
  value: 0.3
hidden_dim:
  desc: null
  value: 512
